version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: william
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  myapp:
    image: wi11i4m/movies
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=william
      - DB_DATABASE=panterest
      - SYMFONY_DATABASE_USERNAME=root
      - SYMFONY_DATABASE_PASSWORD=william
    depends_on:
      - mysql

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
