FROM bitnami/symfony:6.1

EXPOSE 8000

COPY . /app

ENV DB_HOST=mysql
ENV DB_PORT=3306
ENV DB_USERNAME=root
ENV DB_PASSWORD=william
ENV DB_DATABASE=panterest
ENV SYMFONY_DATABASE_USERNAME=root
ENV SYMFONY_DATABASE_PASSWORD=william