name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

### Composer Build Job
  composer-build:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: before action "composer install"
      run: ls -la
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: verify action "composer install"
      run: ls -la
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: vendor-artifact
        path: vendor/
        retention-days: 5

### NodeJS Build Job
  nodejs-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: check project folder
      run: ls -la
    - name: Build
      run: |
        npm install
        npx tailwindcss init -p
        npx tailwindcss -i ./assets/styles/app.css -o ./public/build app.css
    - name: check project folder
      run: ls -la
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: nodejs-artifact
        path: node_modules/
        retention-days: 5

### Docker Build Job
  docker-build:
    needs: [composer-build, nodejs-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: check project folder
        run: ls -la

      - name: Download vendor folder
        uses: actions/download-artifact@v3
        with:
          name: vendor-artifact
      - name: check project folder
        run: ls -la

      - name: Download node_modules folder
        uses: actions/download-artifact@v3
        with:
          name: nodejs-artifact
      - name: check project folder
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/movies