name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-build:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: before action "composer install"
      run: ls -la
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: verify action "composer install"
      run: ls -la
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: vendor-artifact
        path: vendor/
        retention-days: 5

  
  nodejs-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: check project folder
      run: ls -la

    - name: Build
      run: |
        npm install
        npx tailwindcss init -p
        npx tailwindcss -i ./assets/styles/app.css -o ./public/build app.css --watch
        npx webpack

    - name: check project folder
      run: ls -la
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: nodejs-artifact
        path: node_modules/
        retention-days: 5
